[pyprland]
plugins = [
  "scratchpads",
  "workspaces_follow_focus"
]

[scratchpads.dropterm]
animation = "fromTop"
command = "alacritty --class dropterm -e tmux"
class = "dropterm"
margin = 40
size = "80% 65%"
unfocus = "hide"

[scratchpads.spotify]
animation = "fromTop"
class = "Spotify"
command = "spotify-launcher"
lazy = true
margin = 40
size = "80% 65%"
unfocus = "hide"

[scratchpads.network_manager]
animation = "fromTop"
command = "nm-connection-editor"
lazy = true
margin = 40
size = "80% 65%"
unfocus = "hide"

[scratchpads.audio]
animation = "fromTop"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
lazy = true
margin = 40
size = "80% 65%"
unfocus = "hide"

[scratchpads.sysmonitor]
animation = "fromTop"
command = "alacritty --class sysmonitor -e btop"
class = "sysmonitor"
lazy = true
margin = 40
size = "80% 65%"
unfocus = "hide"

[scratchpads.ranger]
animation = "fromTop"
command = "alacritty --class ranger -e ranger"
class = "ranger"
lazy = true
margin = 40
size = "80% 65%"
unfocus = "hide"
