[pyprland]
plugins = [
  "scratchpads",
  "workspaces_follow_focus"
]

[pyprland.variables]
term = "foot --app-id"
term_launch = "-e"

[scratchpads.default.monitor.DP-1]
animation = "fromTop"
margin = 48
size = "75% 60%"
unfocus = "hide"

[scratchpads.default.monitor.DP-3]
animation = "fromTop"
margin = 48
size = "85% 75%"
unfocus = "hide"

[scratchpads.dropterm]
command = "[term] dropterm -e tmux"
class = "dropterm"
use = "default"

[scratchpads.spotify]
class = "Spotify"
command = "spotify-launcher"
lazy = true
use = "default"

[scratchpads.ytmdesktop]
class = "YouTube Music Desktop App"
title = "YouTube Music Desktop App"
command = "youtube-music-desktop-app"
lazy = true
use = "default"
# skip_windowrules = ["aspect", "workspace"]

[scratchpads.network_manager]
command = "nm-connection-editor"
lazy = true
use = "default"

[scratchpads.audio]
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
lazy = true
use = "default"

[scratchpads.sysmonitor]
command = "[term] sysmonitor -e btop"
class = "sysmonitor"
lazy = true
use = "default"

[scratchpads.ranger]
command = "[term] ranger -e ranger"
class = "ranger"
lazy = true
use = "default"
