set $term alacritty 
set $menu rofi -show drun
# Renders icons with -I switch
# set $menu wofi --show drun -I
set $browser qutebrowser
# set $lock wlogout 
set $powerbar nwg-bar
set $lock nwg-lock
set $passman 1password --quick-access
set $screenshot grim -g "$(slurp)"
set $volumecontrol ~/.local/bin/statusbar/volumecontrol
set $volumecontrol_up $volumecontrol up
set $volumecontrol_down $volumecontrol down
set $volumecontrol_mute $volumecontrol mute

# vi: ft=swayconfig
