##############################################################
# Autostart Programs
##############################################################
exec_always "pkill kanshi; kanshi" 
exec_always "~/.local/bin/set-gtk-theme
exec_always "pkill swaybg; swaybg"

exec sworkstyle &> /tmp/sworkstyle.log
exec "/usr/libexec/polkit-gnome-authentication-agent-1"
exec "autotiling -l 2"
exec "/usr/bin/dunst"

# Work Applications
exec "~/Applications/OneDriveGUI-1.0.2-x86_64.AppImage"
exec "/usr/bin/remmina -i"

# exec wl-paste -t text --watch clipman store
#TODO: Add Copy and Paste Functionality with wl-clipboard

# vi: ft=swayconfig
