# Source directory
source = ~/.config/hypr/hyprland.conf.d/*

# Plugins
# plugin = ~/.config/hypr/grab-workspace/grab-workspace.so

# Execute apps
exec-once = $autostart
exec-once = pypr
exec-once = dunstctl set-paused false
exec-once = $HOME/.local/share/hyprload/hyprload.sh
exec = pypr reload
exec = $wm_bar
# exec = $screen_man

# Some default env vars.
env = GDK_BACKEND,wayland,x11
env = QT_STYLE_OVERRIDE,gtk2
env = QT_QPA_PLATFORM,wayland;xcb
# env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
# env = SDL_VIDEODRIVER,wayland
# env = CLUTTER_BACKEND,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

xwayland {
  force_zero_scaling = true
}

monitor = eDP-1, preferred, 0x0, 1.2
monitor = desc:BNQ BenQ PD2710QC L8H0049101Q,2560x1440@60,auto,auto
monitor = ,preferred,auto,auto

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = true
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

general {
    gaps_in = 2
    gaps_out = 4
    border_size = 2
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = master
}

decoration {
    rounding = 6

    blur {
        enabled = true
        size = 10
        passes = 1
        xray = true
    }

    drop_shadow = true
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

animations {
    enabled = true

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

misc {
  # force_default_wallpaper = 0
}

master {
    new_is_master = false
    no_gaps_when_only = 1
    mfact = 0.6
}

gestures {
    workspace_swipe = true
}

device:epic-mouse-v1 {
    sensitivity = -0.5
}

workspace = 1,monitor:desc:BNQ BenQ PD2710QC L8H0049101Q
workspace = 2,monitor:desc:BNQ BenQ PD2710QC L8H0049101Q
workspace = 3,monitor:desc:BNQ BenQ PD2710QC L8H0049101Q
workspace = 4,monitor:desc:BNQ BenQ PD2710QC L8H0049101Q
workspace = 5,monitor:desc:BNQ BenQ PD2710QC L8H0049101Q

# Laptop Lid events
bindl = , switch:off:Lid Switch,exec,hyprctl dispatch dpms on eDP-1
bindl = , switch:on:Lid Switch,exec,hyprctl dispatch dpms off eDP-1
