"$schema" = 'https://starship.rs/config-schema.json'

format = '''
$directory$git_branch$rust$python
$character'''

add_newline = false

palette = 'colors'

[palettes.colors]
mustard = '#af8700' # example
color1 = '{{colors.primary_fixed_dim.default.hex}}'
color2 = '{{colors.on_primary.default.hex}}'
color3 = '{{colors.on_surface_variant.default.hex}}'
color4 = '{{colors.surface_container.default.hex}}'
color5 = '{{colors.on_primary.default.hex}}'
color6 = '{{colors.surface_dim.default.hex}}'
color7 = '{{colors.surface.default.hex}}'
color8 = '{{colors.primary.default.hex}}'
color9 = '{{colors.tertiary.default.hex}}'

# Prompt symbols 
[character]
success_symbol = "[🞈](color9 bold)"
error_symbol = "[🞈](@{error})"
vicmd_symbol = "[🞈](#f9e2af)"

[directory]
format = "[](fg:color1 bg:color4)[󰉋](bg:color1 fg:color2)[ ](fg:color1 bg:color4)[$path ](fg:color3 bg:color4)[ ](fg:color4)"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
format = "[](fg:color8 bg:color4)[ ](bg:color8 fg:color5)[](fg:color8 bg:color4)[(bg:color8 fg:color5) $branch](fg:color3 bg:color4)[](fg:color4) "

[time]
format = "[](fg:color8 bg:color4)[ ](bg:color8 fg:color5)[](fg:color8 bg:color4)[(bg:color8 fg:color5) $time](fg:color3 bg:color4)[](fg:color4) "
disabled = false
time_format = "%R" # Hour:Minute Format

[python]
format = "[](fg:color8 bg:color4)[${symbol}${version}](bg:color8 fg:color5)[](fg:color8 bg:color4)[(bg:color8 fg:color5)( ${virtualenv})](fg:color3 bg:color4)[](fg:color4) "
symbol = '🐍'
# pyenv_version_name = true
pyenv_prefix = 'venv'

[username]
style_user = 'color7 bold'
style_root = 'color0 bold'
format = '[$user]($style) '
disabled = false
show_always = true

[os]
disabled = false
format = "[$symbol]($style) "

[os.symbols]
Arch = "󰣇"
Fedora = ""

[golang]
symbol = "󰟓"

[nix_shell]
impure_msg = '[impure shell](bold color1)'
pure_msg = '[pure shell](bold color2)'
unknown_msg = '[unknown shell](bold color3)'
format = 'via [☃️ $state( \($name\))](bold color4)'

[sudo]
style = 'bold green'
symbol = '󱥠'
disabled = false

[hostname]
disabled = false
ssh_only = true

[line_break]
disabled = true

