$scripts = ~/.local/bin

$pass_man = 1Password
$pass_man_launcher = $pass_man --quick-access

$audio_gui          = pavucontrol
$audio_cli          = playerctl
$audio_cli_toggle   = $audio_cli play-pause
$audio_cli_next     = $audio_cli next
$audio_cli_previous = $audio_cli previous
$audio_script       = $scripts/volumecontrol
$audio_down         = $audio_script down
$audio_up           = $audio_script up
$audio_mute         = $audio_script mute

$brightness         = $scripts/statusbar/brightnesscontrol
$brightness_up      = $brightness up
$brightness_down    = $brightness down

$terminal           = alacritty
$file_manager       = $terminal -e ranger
$sys_montior        = $terminal -e btop

$screenshot         = grim -g "$(slurp)"

$lock               = gtklock

