# Apps for Window Rules
$OneDrive = title:^(OneDriveGUI)$
$Teams = class:(teams)
$OneNote = class:(OneNote)
$Outline = class:(Outline)
$Outlook = class:(Outlook)

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrulev2 = opacity 0.8,class:^(Alacritty)$

windowrulev2 = opacity 0.0 override 0.0 override,class:^(xwaylandvideobridge)$
windowrulev2 = noanim,class:^(xwaylandvideobridge)$
windowrulev2 = nofocus,class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus,class:^(xwaylandvideobridge)$

windowrulev2 = float,$OneDrive
windowrulev2 = move 100%-420 0+36,$OneDrive

windowrulev2 = workspace 5,$Teams
windowrulev2 = stayfocused,title:^(Quick Access — 1Password)$

# These WebApp windows don't tile by default
windowrulev2 = tile,$OneNote

windowrulev2 = tile,$Outline

windowrulev2 = tile,$Outlook
windowrulev2 = workspace 5,$Outlook

