# Scratchpads
$dropterm = ^(dropterm)$
windowrule = float, $dropterm
windowrule = workspace special silent,$dropterm
windowrule = size 75% 60%,$dropterm

$ranger = ^(ranger)$
windowrule = float, $ranger
windowrule = workspace special silent,$ranger
windowrule = size 75% 60%,$ranger

$vpn = ^(Cisco AnyConnect Secure Mobility Client)$
windowrule = float, $vpn
windowrule = workspace special silent,$vpn
windowrule = size 75% 60%,$vpn

$network_manager = ^(nm-connection-editor)$
windowrule = float, $network_manager
windowrule = workspace special silent,$network_manager
windowrule = size 75% 60%,$network_manager

$audio = ^(pavucontrol)$
windowrule = float, $audio
windowrule = workspace special silent,$audio
windowrule = size 75% 60%,$audio

$spotify = title:^(Spotify)$
windowrule = float, $spotify
windowrule = workspace special silent,$spotify
windowrule = size 75% 60%,$spotify

$sysmonitor = ^(sysmonitor)$
windowrule = float, $sysmonitor
windowrule = workspace special silent,$sysmonitor
windowrule = size 75% 60%,$sysmonitor
