# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """ 
[┌>](bold green)$all
[└─>](bold green) """
# Inserts a blank line between shell prompts
add_newline = false

[character]
disabled = true

# Disable the package module, hiding it from the prompt completely
[os]
disabled = false
format = "[$symbol]($style) "

[os.symbols]
Arch = "󰣇"
Fedora = ""

[package]
# disabled = true

[time]
disabled = false

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

[python]
symbol = ""

[golang]
symbol = "󰟓"

[nix_shell]
impure_msg = '[impure shell](bold red)'
pure_msg = '[pure shell](bold green)'
unknown_msg = '[unknown shell](bold yellow)'
format = 'via [☃️ $state( \($name\))](bold blue)'

[sudo]
style = 'bold green'
symbol = '󱥠'
disabled = false

[hostname]
disabled = false
ssh_only = true

[line_break]
disabled = true
