#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config \
  external_bar all:34:0 \
  menubar_opacity 0.0 \
  mouse_follows_focus on \
  focus_follows_mouse on \
  display_arrangement_order default \
  window_origin_display focused \
  window_placement second_child \
  window_zoom_persist on \
  window_shadow on \
  window_animation_duration 0.0 \
  window_animation_easing ease_out_circ \
  window_opacity_duration 0.0 \
  active_window_opacity 1.0 \
  normal_window_opacity 1.0 \
  window_opacity off \
  insert_feedback_color 0xffd75f5f \
  split_ratio 0.60 \
  split_type auto \
  auto_balance off \
  top_padding 4 \
  bottom_padding 4 \
  left_padding 4 \
  right_padding 4 \
  window_gap 04 \
  layout bsp \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap

# Signals
yabai -m signal --add event=application_activated \
  app="^Kitty$" \
  action="yabai -m config border_blur on"
yabai -m signal --add event=application_deactivated \
  app="^Kitty$" \
  action="yabai -m config border_blur off"

# Space Labels
yabai -m space 1 --label 1 --display 1
yabai -m space 2 --label 2 --display 1
yabai -m space 3 --label 3 --display 1
yabai -m space 4 --label 4 --display 1
yabai -m space 5 --label 5 --display 1
yabai -m space 6 --label 6 --display 2
yabai -m space 7 --label 7 --display 2
yabai -m space 8 --label 8 --display 2
yabai -m space 9 --label 9 --display 2
yabai -m space 10 --label 10 --display 2

# Window Rules
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor|Music)$" manage=off grid=7:7:1:1:5:5
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off grid=7:7:1:1:5:5
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off grid=7:7:1:1:5:5
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off grid=7:7:1:1:5:5
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off grid=7:7:1:1:5:5

# Space 1 Rules
yabai -m rule --add app="^(qutebrowser|Microsoft Edge|Safari)" space=1

# Space 2 Rules
yabai -m rule --add title="^Picture-in-Picture$" manage=off grid=5:5:5:5:1:1 sticky=on display=2
yabai -m rule --apply title="^Picture-in-Picture$" manage=off grid=5:5:5:5:1:1 sticky=on display=2

yabai -m rule --add app="^Remote Desktop Manager$" space=3

yabai -m rule --add app="^Obsidian$" space=4

yabai -m rule --add app="^(MSTeams|Microsoft Teams|Microsoft Outlook)$" space=6
yabai -m rule --add app="^Microsoft Teams$" title!="^((Chat|Connect|Teams|Activity|Calendar|Calls|OneDrive) \| * \| Microsoft Teams)$" manage=off grid=7:7:1:1:5:5 space=6

yabai -m rule --add app="^Discord$" space=7

# Scratchpad Rules
yabai -m rule --add app="^alacritty$" title="^btop$" scratchpad=btop grid=5:5:1:0:3:3
yabai -m rule --add app="^alacritty$" title="^scratchterm$" scratchpad=scratchterm grid=5:5:1:0:3:3
yabai -m rule --add app="^kitty$" title="^ranger$" scratchpad=ranger grid=5:5:1:0:3:3
yabai -m rule --add app="^Bitwarden$" scratchpad=bitwarden grid=5:5:1:0:3:3

borders active_color=0xffa7abcc width=5.0 & #inactive_color=0xff3a3b3c width=5.0 &
# borders width=5.0 &
osascript -e 'tell application id "tracesOf.Uebersicht" to refresh' || osascript -e 'tell application id "tracesOf.Uebersicht" to open'

echo "yabai configuration loaded.."
