#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    external_bar                 on :32:0       \
    menubar_opacity              0.0            \
    mouse_follows_focus          on             \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        focus          \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  4              \
    bottom_padding               4              \
    left_padding                 4              \
    right_padding                4              \
    window_gap                   04             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# Window Rules
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Settings$" manage=off grid=4:4:1:1:2:2
# yabai -m rule --add app="^Microsoft Teams$" manage=off

yabai -m rule --add app="^Remote Deskto Manager$" space=3

yabai -m rule --add app="^Obsidian$" space=4

yabai -m rule --add app="^MSTeams$" space=6
yabai -m rule --add app="^Microsoft Teams$" space=6
yabai -m rule --add app="^Microsoft Outlook$" space=6

yabai -m rule --add app="^Discord$" space=7

borders width=5.0 &
echo "yabai configuration loaded.."
