#!/bin/bash

function run {
  if ! pgrep $1 ;
  then
    $@&
  fi
}

session=$(echo $XDG_SESSION_TYPE)

#Find out your monitor name with xrandr or arandr (save and you get this line)

run dunstctl set-paused false

#starting utility applications at boot time
run xfce4-power-manager --daemon
# run /usr/libexec/polkit-gnome-authentication-agent-1 # Fedora location
run /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 # Arch location
run /usr/bin/dunst # Notifications
run /usr/bin/1password --silent
run flatpak run org.remmina.Remmina -i

if [[ $session == "x11" ]]; then
  xset s on
  xset s 150 600
  run xss-lock -- ~/.local/bin/lock -l
  # Xorg Specific Apps
  # Detect Screen Settings
  autorandr -c
  # Run X compositor
  run picom
# Restore Background Image
  run nitrogen --restore
elif [[ $session == "wayland" ]]; then
  # run swaybg -i ~/Pictures/wallpapers/waterfall.png -m fill -o *
  run swayidle
  run kanshi
fi

# Flapaks
run flatpak run org.remmina.Remmina -i

if pgrep packagekitd;
  then
    pkill packagekitd
fi
