#!/bin/bash

# You can call this script like this:
# volumecontrol up
# volumecontrol down
# volumecontrol mute

function get_volume {
    amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

function is_mute {
    amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

function send_notification {
	volume=$(get_volume)
    # Make the bar with the special character ─ (it's not dash -)
    # https://en.wikipedia.org/wiki/Box-drawing_character
  bar=$(seq -s "─" $(($volume/5)) | sed 's/[0-9]//g')
  # Send the notification
  dunstify \
    -r 5556 \
    -u normal \
    -i " " \
    " Volume: $volume" \
    " $bar"
}
function update_icon {
  volume="$(get_volume)"

  if [[ $volume -ge "66" ]]; then
    icon="󰕾"
  elif [[ $volume -ge "34" && $volume -le "65" ]]; then
    icon="󰖀"
  elif [[ $volume -le "33" ]]; then
    icon="󰕿"
  else
    icon="󰝟"
    volume=" M "
  fi

  if is_mute; then
      icon="󰝟"
      volume=" M "
  fi

  printf "%s" "$icon"
}
step=5
# for arg in "$@"; do
# [[ "${arg:0:1}" = '-' ]] || continue
case "$1" in
  up)
    # Set the volume on (if it was muted)
    amixer set Master on > /dev/null
    # Up the volume (+ 2%)
    amixer sset Master $step%+ > /dev/null
    send_notification
  ;;
  down)
    amixer set Master on > /dev/null
    amixer sset Master $step%- > /dev/null
    send_notification
  ;;
  mute)
    # Toggle mute
    amixer set Master 1+ toggle > /dev/null
    if is_mute ; then
    dunstify -i "/usr/share/icons/Adwaita/16x16/legacy/audio-volume-muted.png" -r 5556 -u normal " Volume: Muted" " $bar"
    else
        send_notification
    fi
  ;;
  show)
    send_notification
  ;;
  -s | --step)
    step="$2"
  ;;
  *)
    update_icon
  ;;
esac
# done
exit 0
